from django.contrib import admin
from django.urls import path, include
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name="main"),
    path('skin/', views.skin, name="skin"),
    path('pickaxe/', views.pickaxe, name="pickaxe"),
    path('backpack/', views.backpack, name="backpack"),
    path('emote/', views.emote, name="emote"),
    path('glider/', views.glider, name="glider"),
    path('wrap/', views.wrap, name="wrap"),
    path('music/', views.music, name="music"),
    path('banner/', views.banner, name="banner"),
    path('trail/', views.trail, name="trail"),
    path('screen_load/', views.screen_load, name="screen_load"),
    path('pass/', views.pass1, name="pass1"),
    path('pass2/', views.pass2, name="pass2"),
    path('pass3/', views.pass3, name="pass3"),
    path('pass4/', views.pass4, name="pass4"),
    path('pass5/', views.pass5, name="pass5"),
    path('pass6/', views.pass6, name="pass6"),
    path('pass7/', views.pass7, name="pass7"),
    path('pass8/', views.pass8, name="pass8"),
    path('pass9/', views.pass9, name="pass9"),
    path('pass10/', views.pass10, name="pass10"),
    path('pass11/', views.pass11, name="pass11"),
    path('rarity/', views.rarity, name="rarity"),
    path('skin/rarity/', views.skin_rarity, name="rarity"),
    path('pickaxe/rarity/', views.pickaxe_rarity, name="rarity"),
    path('backpack/rarity/', views.backpack_rarity, name="rarity"),
    path('emote/rarity/', views.emote_rarity, name="rarity"),
    path('glider/rarity/', views.glider_rarity, name="rarity"),
    path('wrap/rarity/', views.wrap_rarity, name="rarity"),
    path('music/rarity/', views.music_rarity, name="rarity"),
    path('banner/rarity/', views.banner_rarity, name="rarity"),
    path('trail/rarity/', views.trail_rarity, name="rarity"),
    path('screen_load/rarity/', views.screen_load_rarity, name="rarity"),
    path('pass/rarity/', views.pass_rarity, name="rarity"),
    path('pass2/rarity/', views.pass2_rarity, name="rarity"),
    path('pass3/rarity/', views.pass3_rarity, name="rarity"),
    path('pass4/rarity/', views.pass4_rarity, name="rarity"),
    path('pass5/rarity/', views.pass5_rarity, name="rarity"),
    path('pass6/rarity/', views.pass6_rarity, name="rarity"),
    path('pass7/rarity/', views.pass7_rarity, name="rarity"),
    path('pass8/rarity/', views.pass8_rarity, name="rarity"),
    path('pass9/rarity/', views.pass9_rarity, name="rarity"),
    path('pass10/rarity/', views.pass10_rarity, name="rarity"),
    path('pass11/rarity/', views.pass11_rarity, name="rarity"),
]
