# Generated by Django 2.2.5 on 2019-12-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='color1',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='color2',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='color3',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
