# Generated by Django 2.2.5 on 2019-12-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191201_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='rarity_sort',
            field=models.IntegerField(default=14),
        ),
    ]
