# Generated by Django 2.2.5 on 2019-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cosmetic_rarity_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
