# Generated by Django 2.2.5 on 2019-12-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cosmetic_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
