# Generated by Django 2.2.5 on 2019-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191205_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='free_pass',
            field=models.BooleanField(default=False),
        ),
    ]
