# Generated by Django 2.2.5 on 2020-02-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cosmetic_search_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='eng_redir',
            field=models.CharField(default='/en/', max_length=50),
        ),
    ]
