# Generated by Django 2.2.5 on 2020-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cosmetic_eng_redir'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemshop',
            name='daily_items',
            field=models.ManyToManyField(related_name='ItemShop_daily', to='main.Cosmetic'),
        ),
        migrations.AddField(
            model_name='itemshop',
            name='featured_items',
            field=models.ManyToManyField(related_name='ItemShop_featured', to='main.Cosmetic'),
        ),
    ]
