# Generated by Django 2.2.5 on 2020-02-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200214_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='last_appearance',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='release_date',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
