# Generated by Django 2.2.5 on 2020-02-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_image_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
