# Generated by Django 2.2.5 on 2020-02-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic_en',
            name='ru_redir',
            field=models.CharField(default='/', max_length=50),
        ),
    ]
