# Generated by Django 2.2.5 on 2020-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0002_cosmetic_en_ru_redir'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemshop_en',
            name='daily_items',
            field=models.ManyToManyField(related_name='ItemShop_en_daily', to='en.Cosmetic_en'),
        ),
        migrations.AddField(
            model_name='itemshop_en',
            name='featured_items',
            field=models.ManyToManyField(related_name='ItemShop_en_featured', to='en.Cosmetic_en'),
        ),
    ]
